version: 2
jobs:
#  build:
#    docker:
#      - image: php 
#    steps:
#      - checkout
#      - run:
#          name: Greeting
#          command: echo Hello, world.
#      - run:
#          name: PHPLint check
#          command: php *.php
  deployment:
    machine:
      php:
        version:  7.0.4
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: find php
          command: find / -name php
      - run:
          name: PHPLint check
          command: php *.php
      - run: 
          name: docker build
          command: docker build  -t itamar/hello-dev:latest .
      - run: 
          name: docker login
          command: docker login -u itamar -p Aa123123
      - run: 
          name: docker push1
          command: docker push itamar/hello-dev
workflows:
  version: 2
  build-deploy:
    jobs:
#      - build
      - deployment
