version: 2
jobs:
  build:
    docker:
      - image: php 
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: PHPLint check
          command: php *.php
  deployment:
    docker:
      - image: alpine/git
    steps:
      - automerge:
          branch: [dev]
          commands:
            - ./merge_to_preprod.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build
          filters:
            branches:
              only: dev
