version: 2
jobs:
  build:
    docker:
      - image: php 
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: PHPLint check
          command: php *.php
    deployment:
      hub:
        branch: dev 
        commands:
          - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
          - docker push itamar/hello-dev
