version: 2
jobs:
  build:
    branches:
      only: dev
    docker:
      - image: php 
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: PHPLint check
          command: php *.php
  deployment:
    branches:
      only: dev
    machine:
      php:
        version: 5.4.5
    steps:
      - checkout
      - run: 
          name: docker build
          command: docker build  -t itamar/hello-dev:latest .
      - run: 
          name: docker login
          command: docker login -u itamar -p Aa123123
      - run: 
          name: docker push1
          command: docker push itamar/hello-dev
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deployment
         filters:
            branches:
              only: dev
