version: 2
jobs:
  build:
    docker:
      - image: php 
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: PHPLint check
          command: php *.php
  deployment:
    docker:
      - image: testim/docker-cli 
    steps:
      - run: 
          name: docker build
          command: docker build  -t itamar/hello-dev:latest .
      - run: 
          name: docker login
          command: docker login -u itamar -p Aa123123
      - run: 
          name: docker pusj
          command: docker push itamar/hello-dev
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deployment
