version: 2
jobs:
  build:
    docker:
      - image: php 
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: PHPLint check
          command: php *.php
    deployment:
      production:
        branch: dev 
        commands:
          - git merge dev pre-prod 
          - git push origin pre-prod
