version: 2
jobs:
  build:
    docker:
      - image: php 
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: PHPLint check
          command: php *.php
    deployment:
      hub:
        commands:
          - docker build  -t itamar/hello-dev:latest .
          - docker login -u itamar -p Aa123123
          - docker push itamar/hello-dev
