version: 2
jobs:
  test:
    docker:
      - image: php 
    steps:
      - checkout
      - run:
          name: PHPLint check
          command: php *.php
  build:
    machine:
      php:
        version:  7.0.4
    steps:
      - checkout
      - run: 
          name: docker build
          command: docker build  -t itamar/hello-dev:latest .
      - run: 
          name: docker login
          command: docker login -u itamar -p Aa123123
      - run: 
          name: docker push1
          command: docker push itamar/hello-dev
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build:
         requires:
         - test
