version: 2
jobs:
  test:
    docker:
      - image: php 
    steps:
      - checkout
      - run:
          name: PHPLint check
          command: php *.php
  build-dev:
    machine:
      php:
        version:  7.0.4
    steps:
      - checkout
      - run: 
          name: docker build
          command: docker build  -t itamar/hello-dev:latest .
      - run: 
          name: docker login
          command: docker login -u itamar -p Aa123123
      - run: 
          name: docker push1
          command: docker push itamar/hello-dev

  build-prod:
    machine:
      php:
        version:  7.0.4
    steps:
      - checkout
      - run:
          name: docker build
          command: docker build  -t itamar/hello-prod:latest .
      - run:
          name: docker login
          command: docker login -u itamar -p Aa123123
      - run:
          name: docker push1
          command: docker push itamar/hello-prod
      - run:
          name: Merge Dev to Master
          command: git checkout master || git merge dev -m "Merge dev to master"
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build-dev:
         requires:
         - test
         filters:
            branches:
              only: dev
      - hold:
         type: approval
         requires:
           - build-dev
      - build-prod:
         requires:
         - hold
         filters:
            branches:
              only: dev
